"""
buttons.py
==========
Все надписи Reply-кнопок собраны в одном месте.
"""

# ─────────────── Главное меню ─────────────────────────────────────
BTN_VIEW_MENU      = "📋 Смотреть меню"
BTN_FILL_PROFILE   = "📱🏠 Заполнить профиль"
BTN_MY_PROFILE     = "👤 Мой профиль"
BTN_OPEN_CART      = "🛒 Открыть корзину"
BTN_CLEAR_CART     = "🗑 Очистить корзину"
BTN_CHANGE_ADDRESS = "🏠 Сменить адрес"
BTN_CHAT_COURIER   = "📩 Чат с доставщиком"
BTN_SUPPORT        = "💡 Поддержка и помощь"
BTN_SEARCH_DISH    = "🔎 Найти блюдо"
BTN_MY_ORDERS      = "📦 Мои заказы"
BTN_ORDER_HISTORY  = "📜 История заказов"
BTN_CHOOSE_COURIER = "🚴 Выбрать Доставщика"
BTN_ADMIN_PANEL    = "⚙️ Админ-панель"
BTN_BACK           = "<< Назад"

# ─────────────── Меню курьера ─────────────────────────────────────
BTN_COURIER_REPORT = "📊 Мой отчёт"
BTN_UNPAID_ORDERS = "📋 Неоплаченные заказы"
BTN_MY_PHONE = "📞 Мой номер для переводов"
# ─────────────── Админ-панель ─────────────────────────────────────
BTN_ADD_DISH         = "🍽️ Добавить блюдо"
BTN_DELETE_DISH      = "❌ Удалить блюдо"
BTN_ADD_PHOTO = "📸 Добавить фото"
BTN_DELETE_PHOTO = "🗑 Удалить фото"
BTN_CATEGORIES       = "📁 Категории"
BTN_FREEZE_DISH      = "🥶 Скрыть блюдо"
BTN_UNFREEZE_DISH    = "☀️ Вернуть блюдо"
BTN_FREEZE_ALL       = "🥶 Скрыть всё меню"
BTN_UNFREEZE_ALL     = "☀️ Показать всё меню"
BTN_LIST_FROZEN      = "📜 Список скрытых блюд"
BTN_MSG_COURIERS     = "📩 Написать Доставщикам"
BTN_USERS_DB         = "👥 База пользователей"
BTN_BROADCAST        = "📢 Сделать рассылку"
BTN_ALL_ORDERS       = "📋 Все заказы"
BTN_FIND_CHAT_ID     = "🆔 Найти чат-ID"
BTN_HIRE_COURIER     = "➕ Нанять Доставщика"
BTN_FIRE_COURIER     = "❌ Уволить Доставщика"
BTN_EDIT_COURIER_PHONE = "📱 Изменить номер Доставщика"
BTN_EDIT_PRICES      = "💰 Редактировать цены"
BTN_DISCOUNTS        = "🏷 Скидки"
BTN_ADMIN_REPORT     = "📊 Отчёт по выручке"
BTN_COURIER_LIST     = "📋 Список Доставщиков"
# ─────────────── Экспорт/Импорт меню ────────────────────────────────
BTN_EXPORT_MENU = "📤 Экспорт меню"
BTN_IMPORT_MENU = "📥 Импорт меню"